# Part 5: Edge Case Testing

## Import Required Libraries

In [2]:
import random
import pandas as pd
from faker import Faker
from datetime import datetime, timedelta

fake = Faker()

### Test 1 What happens when order_items has an order_id not in orders?

In [3]:
orders = pd.read_csv("orders.csv")
items = pd.read_csv("order_itmes.csv")

invalid = items[
~items["order_id"].isin(orders["order_id"])]

invalid

Empty DataFrame
Columns: [item_id, order_id, product_id, quantity, unit_price, discount_percent]
Index: []

### Test 2 What happens when discount_percent > 100?

In [4]:
items = pd.read_csv("order_itmes.csv")

data= items[items["discount_percent"] > 100]
data

Empty DataFrame
Columns: [item_id, order_id, product_id, quantity, unit_price, discount_percent]
Index: []

### Test 3 What happens when quantity is 0?

In [5]:
items = pd.read_csv("order_itmes.csv")

data = items[items["quantity"] == 0]
data

Empty DataFrame
Columns: [item_id, order_id, product_id, quantity, unit_price, discount_percent]
Index: []

### Test 4. What happens when order_date is in the future?

In [6]:
orders = pd.read_csv("orders.csv")

orders["order_date"] = pd.to_datetime(orders["order_date"])
future_date = orders[orders["order_date"] > pd.Timestamp.today()]

future_date

Empty DataFrame
Columns: [order_id, customer_id, order_date, status, region_code]
Index: []