# Part 4: Python + SQL Integration

# Monthly Analysis

## Import Required Libraries

In [27]:
import random
import pandas as pd
from faker import Faker
from datetime import datetime, timedelta

fake = Faker()

## Database Creation

In [28]:
import sqlite3
conn = sqlite3.connect("ecommerce.db")
print("Successfully Database Connected")
cursor = conn.cursor()

Successfully Database Connected

## Helper Function

In [29]:
def run_query(query):
   return pd.read_sql_query(query,conn)

## Table Creation

In [30]:
customers = pd.read_csv("customers.csv")
products = pd.read_csv("cleaned_products.csv")
orders = pd.read_csv("cleaned_orders.csv")
order_items = pd.read_csv("order_itmes.csv")

In [36]:
customers.to_sql("customers",conn,if_exists="replace",index=False)

products.to_sql("products",conn,if_exists="replace",index=False)

orders.to_sql("orders",conn,if_exists="replace",index=False)

order_items.to_sql("order_items",conn,if_exists="replace",index=False)

print("All tables loaded successfully.")

All tables loaded successfully.

## 1. User Input

In [63]:
report_type = input("Enter Report Type (Daily/Weekly/Monthly): ")

start_date = input("Enter Start Date (YYYY-MM-DD): ")

end_date = input("Enter End Date (YYYY-MM-DD): ")

Enter Report Type (Daily/Weekly/Monthly):  monthly
Enter Start Date (YYYY-MM-DD):  2025-01-01
Enter End Date (YYYY-MM-DD):  2025-01-31

## 2. Total Orders

In [65]:
query = f"""
select count(*)
from orders
where date(order_date)
between '{start_date}' and '{end_date}'
"""

df_query = run_query(query)
df_query

   count(*)
0        32

## 3. Total Revenue

In [66]:
query = """SELECT COUNT(*)
FROM order_items oi
JOIN orders o
ON oi.order_id = o.order_id
WHERE DATE(o.order_date)
BETWEEN '2025-01-01' AND '2025-01-31';
"""

df_query = run_query(query)
df_query

   COUNT(*)
0        29

## 4. Unique Customers

In [70]:
query = f"""select count(distinct customer_id) as unique_customers
from orders
where date(order_date)
between '{start_date}'
and '{end_date}'
"""

df_query = run_query(query)
df_query

   unique_customers
0                31

## 5. Top 3 Products

In [71]:
query = f"""select p.product_name, sum(oi.quantity) quantity
from products p
join order_items oi
on p.product_id=oi.product_id
join orders o
on oi.order_id=o.order_id
where date(order_date)
between '{start_date}' and '{end_date}'
group by p.product_name
order by quantity DESC
limit 3
"""
df_query = run_query(query)
df_query

  product_name  quantity
0    Math Book        11
1        Chair        11
2          Pan         9